### PR TITLE
Make connection pool properties configurable

### PR DESCRIPTION
**Pull request by aniketschneider**

### CODE REVIEW

**Comment by dbb613** [comment]
I think someone added me back to the VMC org.  I shouldn't be getting these
anymore.

David

**Comment by jtunney** [comment]
Same goes for me.




jt

**Comment by dbb613** [comment]
Hey mini reunion.  How's it going?  Long time no speak.

David

**Comment by jtunney** [comment]
Indeed!

I'm doing well, thanks. Busy with another start up. Lots of fun!

And y'all?


jt

On Wednesday, July 15, 2015, dbb613 <notifications@github.com> wrote:

> Hey mini reunion. How's it going? Long time no speak.
>
> David
> On Jul 15, 2015 5:49 PM, "Jason Tunney" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Same goes for me.
> >
> >
> >
> >
> > jt
> >
> > On Wed, Jul 15, 2015 at 5:42 PM, dbb613 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > I think someone added me back to the VMC org. I shouldn't be getting
> > these
> > > anymore.
> > > David
> > > On Jul 15, 2015 3:37 PM, "Aniket Schneider" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > > wrote:
> > >> ------------------------------
> > >> You can view, comment on, or merge this pull request online at:
> > >>
> > >> https://github.com/vmcbos/trident-redis/pull/4
> > >> Commit Summary
> > >>
> > >> - Make connection pool properties configurable
> > >>
> > >> File Changes
> > >>
> > >> - *M* pom.xml
> > >> <https://github.com/vmcbos/trident-redis/pull/4/files#diff-0> (2)
> > >> - *M* src/main/java/storm/trident/redis/IJedisPoolFactory.java
> > >> <https://github.com/vmcbos/trident-redis/pull/4/files#diff-1> (28)
> > >> - *A*
> > >>
> >
> src/main/java/storm/trident/redis/connection/AbstractJedisPoolFactory.java
> > >> <https://github.com/vmcbos/trident-redis/pull/4/files#diff-2> (26)
> > >> - *M*
> > >> src/main/java/storm/trident/redis/connection/JedisPoolFactory.java
> > >> <https://github.com/vmcbos/trident-redis/pull/4/files#diff-3> (11)
> > >> - *M*
> > >>
> >
> src/main/java/storm/trident/redis/connection/SentinelJedisPoolFactory.java
> > >> <https://github.com/vmcbos/trident-redis/pull/4/files#diff-4> (9)
> > >>
> > >> Patch Links:
> > >>
> > >> - https://github.com/vmcbos/trident-redis/pull/4.patch
> > >> - https://github.com/vmcbos/trident-redis/pull/4.diff
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <https://github.com/vmcbos/trident-redis/pull/4>.
> > >>
> > > ---
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/vmcbos/trident-redis/pull/4#issuecomment-121758842
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vmcbos/trident-redis/pull/4#issuecomment-121760193>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vmcbos/trident-redis/pull/4#issuecomment-121763050>.
>


-- 
"I remember trolling by morse code back when slashdot was a ham radio
channel"

**Comment by mmao** [comment]
Sorry, fellas, we've been working on a storm load issue and going to the
underlayers to tweak things.
Guess we didn't fix up the notifications on this one.

But it is good to hear from you :)

On Wed, Jul 15, 2015 at 6:07 PM, Jason Tunney <notifications@github.com>
wrote:

> Indeed!
>
> I'm doing well, thanks. Busy with another start up. Lots of fun!
>
> And y'all?
>
>
> jt
>
> On Wednesday, July 15, 2015, dbb613 <notifications@github.com> wrote:
>
> > Hey mini reunion. How's it going? Long time no speak.
> >
> > David
> > On Jul 15, 2015 5:49 PM, "Jason Tunney" <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > Same goes for me.
> > >
> > >
> > >
> > >
> > > jt
> > >
> > > On Wed, Jul 15, 2015 at 5:42 PM, dbb613 <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > >
> > > > I think someone added me back to the VMC org. I shouldn't be getting
> > > these
> > > > anymore.
> > > > David
> > > > On Jul 15, 2015 3:37 PM, "Aniket Schneider" <
> notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > > > wrote:
> > > >> ------------------------------
> > > >> You can view, comment on, or merge this pull request online at:
> > > >>
> > > >> https://github.com/vmcbos/trident-redis/pull/4
> > > >> Commit Summary
> > > >>
> > > >> - Make connection pool properties configurable
> > > >>
> > > >> File Changes
> > > >>
> > > >> - *M* pom.xml
> > > >> <https://github.com/vmcbos/trident-redis/pull/4/files#diff-0> (2)
> > > >> - *M* src/main/java/storm/trident/redis/IJedisPoolFactory.java
> > > >> <https://github.com/vmcbos/trident-redis/pull/4/files#diff-1> (28)
> > > >> - *A*
> > > >>
> > >
> >
> src/main/java/storm/trident/redis/connection/AbstractJedisPoolFactory.java
> > > >> <https://github.com/vmcbos/trident-redis/pull/4/files#diff-2> (26)
> > > >> - *M*
> > > >> src/main/java/storm/trident/redis/connection/JedisPoolFactory.java
> > > >> <https://github.com/vmcbos/trident-redis/pull/4/files#diff-3> (11)
> > > >> - *M*
> > > >>
> > >
> >
> src/main/java/storm/trident/redis/connection/SentinelJedisPoolFactory.java
> > > >> <https://github.com/vmcbos/trident-redis/pull/4/files#diff-4> (9)
> > > >>
> > > >> Patch Links:
> > > >>
> > > >> - https://github.com/vmcbos/trident-redis/pull/4.patch
> > > >> - https://github.com/vmcbos/trident-redis/pull/4.diff
> > > >>
> > > >> —
> > > >> Reply to this email directly or view it on GitHub
> > > >> <https://github.com/vmcbos/trident-redis/pull/4>.
> > > >>
> > > > ---
> > > > Reply to this email directly or view it on GitHub:
> > > >
> https://github.com/vmcbos/trident-redis/pull/4#issuecomment-121758842
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/vmcbos/trident-redis/pull/4#issuecomment-121760193
> >.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vmcbos/trident-redis/pull/4#issuecomment-121763050>.
> >
>
>
> --
> "I remember trolling by morse code back when slashdot was a ham radio
> channel"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vmcbos/trident-redis/pull/4#issuecomment-121764061>.
>

-- 
*NOTICE TO RECIPIENT:* The contents of this e-mail message and any 
attachments are intended for the addressee(s) named in this message. This 
communication is intended to be and to remain confidential and may be 
subject to applicable client/employee and/or work product privileges. If 
you are not the intended recipient of this message, or if this message has 
been addressed to you in error, please immediately alert the sender by 
reply e-mail and then delete this message and its attachments. Do not 
deliver, distribute or copy this message and/or any attachments and, if you 
are not the intended recipient, do not disclose the contents or take any 
action in reliance upon the information contained in this communication or 
any attachments.

**Comment by ru2nuts** [comment]
Felt like old times :)

**Comment by parnold** [comment]
Nice to see all you guys!

It's because this is a public fork of another repo, so we cannot make it private. You guys just need to go into the repo and click on the "unwatch" button at the top and it'll stop sending you updates.

JT, I thought of you when we were in Montreal a few weekends ago; I hope you're doing well!

Alex, don't be a stranger, what, 30 feet from our building!

**Comment by jtunney** [comment]
Like the good old times for sure!


Perry, I’m only about an hour-45 away from Montreal, but a few weekends ago I was just 20 minutes away!  Y’all come to my part of the world, you *must* let me know.  It’s a Canadian rule. :)

**Comment by mmao** [comment]
We already checked out Alex's place during some secret video project
shooting time. It's pretty nice, though it's like having 100 neighbors
around you at all times.

On Thu, Jul 16, 2015 at 9:16 AM, Jason Tunney <notifications@github.com>
wrote:

> Like the good old times for sure!
>
>
> Perry, I’m only about an hour-45 away from Montreal, but a few weekends
> ago I was just 20 minutes away!  Y’all come to my part of the world, you
> *must* let me know.  It’s a Canadian rule. :)
>
> On Thu, Jul 16, 2015 at 9:12 AM, parnold <notifications@github.com> wrote:
>
> > Nice to see all you guys!
> > It's because this is a public fork of another repo, so we cannot make it
> private. You guys just need to go into the repo and click on the "unwatch"
> button at the top and it'll stop sending you updates.
> > JT, I thought of you when we were in Montreal a few weekends ago; I hope
> you're doing well!
> > Alex, don't be a stranger, what, 30 feet from our building!
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/vmcbos/trident-redis/pull/4#issuecomment-121951875
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vmcbos/trident-redis/pull/4#issuecomment-121952724>.
>

-- 
*NOTICE TO RECIPIENT:* The contents of this e-mail message and any 
attachments are intended for the addressee(s) named in this message. This 
communication is intended to be and to remain confidential and may be 
subject to applicable client/employee and/or work product privileges. If 
you are not the intended recipient of this message, or if this message has 
been addressed to you in error, please immediately alert the sender by 
reply e-mail and then delete this message and its attachments. Do not 
deliver, distribute or copy this message and/or any attachments and, if you 
are not the intended recipient, do not disclose the contents or take any 
action in reliance upon the information contained in this communication or 
any attachments.

**Pull request merged**
